
---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:testdb

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:~/dev
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: integration
  datasource:
    url: jdbc:h2:mem:testdb
